
version: 'v2.24.3-desktop.1'

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
      - SECRET_KEY=test